---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-servicemonitor
  namespace: default
  labels:
    app: nginx-ingress-servicemonitor
spec:
  ports:
    - name: prometheus
      protocol: TCP
      port: 9113
      targetPort: 9113
  selector:
    app: nginx-ingress
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-servicemonitor
  namespace: default
  labels:
    app: nginx-ingress-servicemonitor
spec:
  selector:
    matchLabels:
      app: nginx-ingress-servicemonitor
  endpoints:
    - port: prometheus
