---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-servicemonitor
  namespace: monitoring
  labels:
    app: nginx-ingress-servicemonitor
spec:
  ports:
    - name: prometheus
      protocol: TCP
      port: 10254
      targetPort: 10254
  selector:
    app: nginx-ingress
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-servicemonitor
  namespace: monitoring
  labels:
    app: nginx-ingress-servicemonitor
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nginx-ingress-servicemonitor
  namespaceSelector:
    matchNames:
      - ingress
  endpoints:
    - port: prometheus