apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: scrooge-bank-secrets-provider
  namespace: default
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    region: ap-southeast-1
    objects: |
      - objectName: "rds!cluster-c5d7d9d6-cc9d-485f-8730-bb4af8ce0e7e"
        objectType: secretsmanager
        jmesPath:
          - path: username
            objectAlias: db_username
          - path: password
            objectAlias: db_password
      - objectName: JWTPrivateKey
        objectType: secretsmanager
        versionStage: AWSCURRENT
        objectAlias: jwt_private_key
      - objectName: rds-write-endpoint
        objectType: secretsmanager
        versionStage: AWSCURRENT
        objectAlias: spring_datasource_host
      - objectName: "docdb-credentials"
        objectType: secretsmanager
        jmesPath:
          - path: username
            objectAlias: docdb_username
          - path: password
            objectAlias: docdb_password
      - objectName: docdb-write-endpoint
        objectType: secretsmanager
        versionStage: AWSCURRENT
        objectAlias: docdb_host
      - objectName: kafka-write-endpoint
        objectType: secretsmanager
        versionStage: AWSCURRENT
        objectAlias: kafka_bootstrap_servers
  secretObjects:
    - secretName: db-credentials
      type: Opaque
      data:
        - objectName: db_username
          key: k8s-db-username
        - objectName: db_password
          key: k8s-db-password
    - secretName: jwt-private-key
      type: Opaque
      data:
        - objectName: jwt_private_key
          key: k8s-jwt-private-key
    - secretName: db-host
      type: Opaque
      data:
        - objectName: spring_datasource_host
          key: k8s-spring-datasource-host
    - secretName: docdb-host
      type: Opaque
      data:
        - objectName: docdb_host
          key: k8s-spring-datasource-host-docdb
    - secretName: docdb-k8s-credentials
      type: Opaque
      data:
        - objectName: docdb_username
          key: k8s-docdb-username
    - secretName: docdb-credentials
      type: Opaque
      data:
        - objectName: docdb_password
          key: k8s-docdb-password
    - secretName: kafka-host
      type: Opaque
      data:
        - objectName: kafka_bootstrap_servers
          key: k8s-kafka-host
