apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: scrooge-bank-secrets-provider
  namespace: default
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    region: ap-southeast-1
    objects: |
      - objectName: "rds!cluster-*"
        objectType: secretsmanager
        jmesPath:
          - path: username
            objectAlias: db_username
          - path: password
            objectAlias: db_password
      - objectName: JWTPrivateKey
        objectType: secretsmanager
        versionStage: AWSCURRENT
        objectAlias: jwt_private_key
  secretObjects:
    - secretName: db-k8s-secret
      type: Opaque
      data:
        - objectName: db_username
          key: k8s-db-username
        - objectName: db_password
          key: k8s-db-password
        - objectName: jwt_private_key
          key: k8s-jwt-private-key
