apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: scrooge-bank-secrets-provider
  namespace: default
spec:
  provider: aws
  parameters:
    region: ap-southeast-1
    objects: |
      - objectName: "rds!cluster-d47fba38-4036-4bda-9ddb-a5f7e680ad98"
        objectType: secretsmanager
        jmesPath:
          - path: username
            objectAlias: db_username
          - path: password
            objectAlias: db_password
      - objectName: JWTPrivateKey
        objectType: secretsmanager
        versionStage: AWSCURRENT
        objectAlias: jwt_private_key
      - objectName: rds-write-endpoint
        objectType: secretsmanager
        versionStage: AWSCURRENT
        objectAlias: spring_datasource_host
  secretObjects:
    - secretName: db-k8s-secret
      type: Opaque
      data:
        - objectName: db_username
          key: k8s-db-username
        - objectName: db_password
          key: k8s-db-password
        - objectName: jwt_private_key
          key: k8s-jwt-private-key
        - objectName: spring_datasource_host
          key: k8s-spring-datasource-host
