apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-ca-cert
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
data:
  global-bundle.pem: |
{{ .Files.Get "global-bundle.pem" | indent 4 }}
